kind: pipeline
type: docker
name: deploy

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

steps:
  - name: docker_build
    image: thegeeklab/drone-docker-buildx:23
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - echo "$CI_REGISTRY_PASSWORD" | docker login registry.gitlab.com -u "$CI_REGISTRY_USER" --password-stdin
      - sleep 15
      - ls -l
      - docker buildx create --use --platform=linux/arm64,linux/amd64 --name multi-platform-builder
      - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag registry.gitlab.com/bignoise/images/icecast:build${DRONE_BUILD_NUMBER} . -f Dockerfile
    environment:
      CI_REGISTRY_USER:
        from_secret: username
      CI_REGISTRY_PASSWORD:
        from_secret: password
    settings:
      repo: registry.gitlab.com/bignoise/images/icecast
      registry: registry.gitlab.com
      username:
        from_secret: username
      password:
        from_secret: password
      platforms:
        - linux/arm64/v8
      tags: build${DRONE_BUILD_NUMBER}-arm64v8
volumes:
  - name: dockersock
    temp: {}
  - name: static
    temp: {}
---
kind: secret
name: username
get:
  path: kv/bignoise/docker
  name: username

---
kind: secret
name: password
get:
  path: kv/bignoise/docker
  name: password
