kind: pipeline
type: docker
name: build

steps:
- name: build
  image: rust:1.75-alpine3.18
  commands:
  - cargo build --release --target x86_64-unknown-linux-musl
  - cargo build --release --target aarch64-unknown-linux-musl
